language: node_js
node_js:
- node
dist: trusty
sudo: false
notifications:
  email:
    on_success: change
    on_failure: always
install:
- npm i -g npm@5.7.1
- npm ci
before_deploy:
- rm -rf node_modules
deploy:
  skip_cleanup: true
  provider: heroku
  app: node-docker-client
  api_key:
    secure: meIvDr+w3qf85wiPOL9pf2lCanttXLZUribK7XJdPpODTjXlAqlKbX3Hw9NGKSqjw8Nc036l062Nmmh8B8XCTWd5oxb5Ab781GarKyssoP9+385Q8PflEvxIIsoN4dmfxdTCC/vishBp0JuhRIbiIydAvp11+nffkOI9jWBi0OFqP+17lcI/1tIjkhXxrayqBQTkYOVPLY0XV45MRrSPYhycQCTamKohGat82fdzEpAAZYAy5JXI3aGSQPrLb0aOJWQTjNhaE+7E/31FZrQJql+d33zjEseatQm6navNCFBROZlo9fex5gkFr8oFcrQ8758bSVKg33zvYKmX561lRRKq0YS2Q/fz0sn2k3WdbgSZlqxWv7Rk66/21EIaMf9RU2fO7gcQ8luHBW+snXtMhq68DLjaPkomFzjo8rByqNvgJXqJDte8/aYIiB6L4BzpM9TA9SVF8yMLVbSeVInUfCygMd3/g1wEPt0EQaJJ8Vzx8ny47DonPet5/cBce1svImsg1vgGbKDdXrSPNOYvwMIkKlnPStKM8cuWPsy9GNvQn+Iya50jA1eIAnJ54giPDUGDAo9nyl25WEaZIXcG81s1vM2h2UXU2v0Ky2bTg8gThzl5byFK6J/6G6rlt4lGhRtITWX2qWJKJf6RVW33YXEyubtl6JpLPhuvn5XYfng=
